#!/usr/bin/env bash
#
# Regenerate live_stt/pb/ from proto/livestt/v1/asr.proto.
#
# The whole directory is a build artifact (gitignored) -- invoked by build.sh,
# test.sh, and the Dockerfile so nobody has to remember to run it by hand.
#
# Why the __init__.py shim: grpc_tools.protoc mirrors the .proto file's path
# relative to -I in its output, so asr.proto living at proto/livestt/v1/asr.proto
# produces live_stt/pb/livestt/v1/asr_pb2.py, and the generated *_grpc.py imports
# its sibling module as `from livestt.v1 import asr_pb2` (package-path import,
# not a relative one). That only resolves if live_stt/pb/ itself is on
# sys.path, hence live_stt/pb/__init__.py inserts itself there on import.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.."

PB_DIR="live_stt/pb"

# Prefer the project venv (see test.sh) -- grpc_tools is not on the system
# python's path, and cp314 wheel coverage for grpcio-tools is recent enough
# that a stray system python may not have it either.
PYTHON="python3"
[ -x "venv/bin/python" ] && PYTHON="venv/bin/python"

rm -rf "$PB_DIR"
mkdir -p "$PB_DIR"

"$PYTHON" -m grpc_tools.protoc \
    -I proto \
    --python_out="$PB_DIR" \
    --grpc_python_out="$PB_DIR" \
    --pyi_out="$PB_DIR" \
    proto/livestt/v1/asr.proto

cat > "$PB_DIR/__init__.py" <<'EOF'
"""Generated protobuf/grpc stubs. Regenerated by scripts/gen_proto.sh -- not
checked in (see .gitignore).

The generated *_grpc.py imports its sibling pb2 module via the proto package
path (``from livestt.v1 import asr_pb2``), not a relative import, so this
directory must be importable as a root in its own right.
"""

import os
import sys

_PB_DIR = os.path.dirname(__file__)
if _PB_DIR not in sys.path:
    sys.path.insert(0, _PB_DIR)
EOF

# protoc does not create __init__.py for the package directories it mirrors.
find "$PB_DIR/livestt" -type d -exec touch {}/__init__.py \;

echo "==> Generated $PB_DIR from proto/livestt/v1/asr.proto"
